/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin_basics_1

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class KotlinBasicsTest {

    @Test
    fun testReverseString() {
        assertEquals("olleH", reverseString("Hello"))
        assertEquals("!dlrow ,olleH", reverseString("Hello, world!"))
    }

    @Test
    fun testFizzBuzz() {
        fizzBuzz()
    }

    @Test
    fun testCleanString() {
        assertEquals("helloworld", cleanString("Hello World"))
        assertEquals("hello", cleanString("   HeLlO   "))
    }

    @Test
    fun testIsPalindrome() {
        assertTrue(isPalindrome("radar"))
        assertTrue(isPalindrome("A man a plan a canal Panama"))
        assertFalse(isPalindrome("hello"))
    }

    @Test
    fun testFindNthFibonacci() {
        assertEquals(0, findNthFibonacci(0))
        assertEquals(1, findNthFibonacci(1))
        assertEquals(1, findNthFibonacci(2))
        assertEquals(2, findNthFibonacci(3))
        assertEquals(3, findNthFibonacci(4))
        assertEquals(5, findNthFibonacci(5))
        assertEquals(8, findNthFibonacci(6))
        assertEquals(13, findNthFibonacci(7))
    }
}
